/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.css",
  ],
  safelist: [
    "ds-focus",
    "ds-hover",
    "ds-active",
  ],
  theme: {
    extend: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        white: '#ffffff',
        black: '#1f2331',
        'neutral-dark': '#5e616b',
        'neutral-base': '#92949b',
        'neutral-light': '#ededec',
        'neutral-lighter': '#f6f6f5',
        'primary-base': '#00607a',
        'primary-light': '#d6eaf0',
        'primary-dark': '#00475c',
        'success-base': '#24d14c',
        'success-light': '#dcf8e2',
        'success-dark': '#1aa23a',
        'warning-base': '#fdcb33',
        'warning-light': '#fef6b2',
        'warning-dark': '#b88e12',
        'info-base': '#fa9902',
        'info-light': '#feebcc',
        'info-dark': '#c97a00',
        'alert-base': '#d22333',
        'alert-light': '#fbd3ce',
        'alert-dark': '#a40014',
        'heading-base': '#3c4c5c',
        'heading-dark': '#26374a',
        code: '#c10007',
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'base': '1rem',
        'lg': '1.75rem',
        'xl': '2.5rem',
        '2xl': '5rem',
        '3xl': '10rem',
      },
      fontFamily: {
        sans: ['"Open Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'outline-warning': '0 0 0 3px var(--color-warning-base)',
        'outline-alert': '0 0 0 2px var(--color-alert-base)',
        'solid-primary-base': '0 1px 0 0 var(--color-primary-base)',
        'solid-primary-light': '0 1px 0 0 var(--color-primary-light)',
        'solid-primary-dark': '0 1px 0 0 var(--color-primary-dark)',
        'solid-alert-base': '0 1px 0 0 var(--color-alert-base)',
        'solid-alert-dark': '0 1px 0 0 var(--color-alert-dark)',
        'solid-neutral-base': '0 1px 0 0 var(--color-neutral-base)',
        'solid-black': '0 1px 0 0 var(--color-black)',
        'outline-black': '0 0 0 3px var(--color-black)',
        'outline-focus': 'inset 0 -2px 0 0 var(--color-black)',
        'outline-focus-input': 'inset 0 0 0 3px var(--color-black)',
      },
      borderRadius: {
        DEFAULT: '0.1875rem',
      },
      maxWidth: {
        'xs': '20rem',
        'sm': '24rem',
        'md': '28rem',
        'lg': '32rem',
        'xl': '36rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
