// CSS pre-processor: replaces @apply with CSS values before Tailwind processes
import fs from 'fs';
import path from 'path';
import postcssImport from 'postcss-import';
import postcssNesting from 'postcss-nesting';
import postcss from 'postcss';

// Map of Tailwind utilities to CSS values (including !important variants)
const UTILITIES = {
  // Display
  'hidden': 'display: none',
  'block': 'display: block',
  'inline-block': 'display: inline-block',
  'inline': 'display: inline',
  'flex': 'display: flex',
  'inline-flex': 'display: inline-flex',
  'grid': 'display: grid',
  'contents': 'display: contents',
  'list-item': 'display: list-item',
  'none': 'display: none',
  'visible': 'visibility: visible',
  'invisible': 'visibility: hidden',

  // Position
  'absolute': 'position: absolute',
  'relative': 'position: relative',
  'fixed': 'position: fixed',
  'static': 'position: static',
  'sticky': 'position: sticky',

  // Top/right/bottom/left
  'top-0': 'top: 0',
  'top-full': 'top: 100%',
  'right-0': 'right: 0',
  'bottom-0': 'bottom: 0',
  'left-0': 'left: 0',
  'inset-0': 'top: 0; right: 0; bottom: 0; left: 0',
  'inset-y-0': 'top: 0; bottom: 0',
  '-top-sm': 'top: -0.5rem',
  '-top-px': 'top: -1px',
  '-top-0\\.5': 'top: -0.125rem',
  '-translate-y-0': '--tw-translate-y: 0; transform: translateY(0)',
  '-translate-y-full': '--tw-translate-y: -100%; transform: translateY(-100%)',
  'translate-y-0': '--tw-translate-y: 0; transform: translateY(0)',

  // Flexbox
  'flex-1': 'flex: 1 1 0%',
  'flex-auto': 'flex: 1 1 auto',
  'flex-none': 'flex: none',
  'flex-wrap': 'flex-wrap: wrap',
  'flex-nowrap': 'flex-wrap: nowrap',
  'flex-col': 'flex-direction: column',
  'flex-row': 'flex-direction: row',
  'items-center': 'align-items: center',
  'items-start': 'align-items: flex-start',
  'items-end': 'align-items: flex-end',
  'items-stretch': 'align-items: stretch',
  'justify-center': 'justify-content: center',
  'justify-between': 'justify-content: space-between',
  'justify-around': 'justify-content: space-around',
  'justify-start': 'justify-content: flex-start',
  'justify-end': 'justify-content: flex-end',
  'self-start': 'align-self: flex-start',
  'self-center': 'align-self: center',
  'order-1': 'order: 1',
  'order-2': 'order: 2',
  'order-3': 'order: 3',
  'order-first': 'order: -9999',
  'order-last': 'order: 9999',
  'basis-full': 'flex-basis: 100%',
  'basis-auto': 'flex-basis: auto',
  'grow': 'flex-grow: 1',
  'shrink-0': 'flex-shrink: 0',
  'shrink': 'flex-shrink: 1',

  // Grid
  'grid-cols-1': 'grid-template-columns: repeat(1, minmax(0, 1fr))',
  'grid-cols-2': 'grid-template-columns: repeat(2, minmax(0, 1fr))',
  'grid-cols-3': 'grid-template-columns: repeat(3, minmax(0, 1fr))',
  'grid-cols-4': 'grid-template-columns: repeat(4, minmax(0, 1fr))',
  'col-span-2': 'grid-column: span 2 / span 2',
  'col-span-3': 'grid-column: span 3 / span 3',
  'col-span-4': 'grid-column: span 4 / span 4',
  'col-span-full': 'grid-column: 1 / -1',
  'col-start-2': 'grid-column-start: 2',
  'row-span-2': 'grid-row: span 2 / span 2',

  // Gap
  'gap-0': 'gap: 0',
  'gap-xs': 'gap: 0.25rem',
  'gap-sm': 'gap: 0.5rem',
  'gap-base': 'gap: 1rem',
  'gap-lg': 'gap: 1.75rem',
  'gap-xl': 'gap: 2.5rem',
  'gap-x-sm': 'column-gap: 0.5rem',
  'gap-y-sm': 'row-gap: 0.5rem',
  'gap-x-base': 'column-gap: 1rem',
  'gap-y-base': 'row-gap: 1rem',

  // Width/Height
  'w-full': 'width: 100%',
  'w-auto': 'width: auto',
  'w-screen': 'width: 100vw',
  'w-1/2': 'width: 50%',
  'w-1/3': 'width: 33.333333%',
  'w-2/3': 'width: 66.666667%',
  'w-3/4': 'width: 75%',
  'w-4/5': 'width: 80%',
  'w-xs': 'width: 20rem',
  'w-sm': 'width: 24rem',
  'w-md': 'width: 28rem',
  'w-lg': 'width: 32rem',
  'w-6': 'width: 1.5rem',
  'w-8': 'width: 2rem',
  'w-10': 'width: 2.5rem',
  'w-12': 'width: 3rem',
  'w-16': 'width: 4rem',
  'w-20': 'width: 5rem',
  'w-24': 'width: 6rem',
  'w-px': 'width: 1px',
  'h-full': 'height: 100%',
  'h-screen': 'height: 100vh',
  'h-auto': 'height: auto',
  'h-6': 'height: 1.5rem',
  'h-8': 'height: 2rem',
  'h-10': 'height: 2.5rem',
  'h-12': 'height: 3rem',
  'h-16': 'height: 4rem',
  'h-px': 'height: 1px',
  'h-max': 'height: max-content',
  'max-w-full': 'max-width: 100%',
  'max-w-xs': 'max-width: 20rem',
  'max-w-sm': 'max-width: 24rem',
  'max-w-md': 'max-width: 28rem',
  'max-w-lg': 'max-width: 32rem',
  'max-w-xl': 'max-width: 36rem',
  'max-w-2xl': 'max-width: 42rem',
  'min-w-0': 'min-width: 0',
  'min-h-screen': 'min-height: 100vh',
  'max-h-none': 'max-height: none',
  'max-h-screen': 'max-height: 100vh',
  'max-h-96': 'max-height: 24rem',
  'max-h-max': 'max-height: max-content',

  // Spacing (margin)
  'm-0': 'margin: 0',
  'm-auto': 'margin: auto',
  'mx-auto': 'margin-left: auto; margin-right: auto',
  'my-auto': 'margin-top: auto; margin-bottom: auto',
  'mt-0': 'margin-top: 0',
  'mt-xs': 'margin-top: 0.25rem',
  'mt-sm': 'margin-top: 0.5rem',
  'mt-base': 'margin-top: 1rem',
  'mt-lg': 'margin-top: 1.75rem',
  'mt-xl': 'margin-top: 2.5rem',
  'mt-auto': 'margin-top: auto',
  'mt-px': 'margin-top: 1px',
  'mt-0\\.5': 'margin-top: 0.125rem',
  'mt-1': 'margin-top: 0.25rem',
  'mt-2': 'margin-top: 0.5rem',
  'mt-3': 'margin-top: 0.75rem',
  'mt-4': 'margin-top: 1rem',
  'mt-6': 'margin-top: 1.5rem',
  'mt-8': 'margin-top: 2rem',
  'mt-10': 'margin-top: 2.5rem',
  'mt-12': 'margin-top: 3rem',
  'mt-16': 'margin-top: 4rem',
  'mt-20': 'margin-top: 5rem',
  'mt-24': 'margin-top: 6rem',
  'mt-32': 'margin-top: 8rem',
  '-mt-xs': 'margin-top: -0.25rem',
  '-mt-sm': 'margin-top: -0.5rem',
  '-mt-base': 'margin-top: -1rem',
  '-mt-lg': 'margin-top: -1.75rem',
  '-mt-1': 'margin-top: -0.25rem',
  '-mt-2': 'margin-top: -0.5rem',
  '-mt-4': 'margin-top: -1rem',
  '-mt-6': 'margin-top: -1.5rem',
  'mb-0': 'margin-bottom: 0',
  'mb-xs': 'margin-bottom: 0.25rem',
  'mb-sm': 'margin-bottom: 0.5rem',
  'mb-base': 'margin-bottom: 1rem',
  'mb-lg': 'margin-bottom: 1.75rem',
  'mb-xl': 'margin-bottom: 2.5rem',
  'mb-auto': 'margin-bottom: auto',
  'mb-px': 'margin-bottom: 1px',
  'mb-1': 'margin-bottom: 0.25rem',
  'mb-2': 'margin-bottom: 0.5rem',
  'mb-4': 'margin-bottom: 1rem',
  'mb-6': 'margin-bottom: 1.5rem',
  'mb-8': 'margin-bottom: 2rem',
  'mb-16': 'margin-bottom: 4rem',
  'ml-0': 'margin-left: 0',
  'ml-xs': 'margin-left: 0.25rem',
  'ml-sm': 'margin-left: 0.5rem',
  'ml-base': 'margin-left: 1rem',
  'ml-lg': 'margin-left: 1.75rem',
  'ml-xl': 'margin-left: 2.5rem',
  'ml-auto': 'margin-left: auto',
  'ml-px': 'margin-left: 1px',
  'ml-1': 'margin-left: 0.25rem',
  'ml-2': 'margin-left: 0.5rem',
  'ml-4': 'margin-left: 1rem',
  'ml-6': 'margin-left: 1.5rem',
  'ml-8': 'margin-left: 2rem',
  'ml-16': 'margin-left: 4rem',
  'mr-0': 'margin-right: 0',
  'mr-xs': 'margin-right: 0.25rem',
  'mr-sm': 'margin-right: 0.5rem',
  'mr-base': 'margin-right: 1rem',
  'mr-lg': 'margin-right: 1.75rem',
  'mr-auto': 'margin-right: auto',
  'mr-px': 'margin-right: 1px',
  'mr-1': 'margin-right: 0.25rem',
  'mr-2': 'margin-right: 0.5rem',
  'mr-4': 'margin-right: 1rem',
  'mr-6': 'margin-right: 1.5rem',
  'mr-8': 'margin-right: 2rem',
  'mr-16': 'margin-right: 4rem',
  '-mr-xs': 'margin-right: -0.25rem',
  '-mr-sm': 'margin-right: -0.5rem',
  '-mr-base': 'margin-right: -1rem',
  '-mr-lg': 'margin-right: -1.75rem',
  '-mr-1': 'margin-right: -0.25rem',
  '-mr-2': 'margin-right: -0.5rem',
  '-mr-4': 'margin-right: -1rem',
  '-mr-6': 'margin-right: -1.5rem',
  '-mb-0\\.5': 'margin-bottom: -0.125rem',
  '-mb-px': 'margin-bottom: -1px',

  // Padding
  'p-0': 'padding: 0',
  'p-xs': 'padding: 0.25rem',
  'p-sm': 'padding: 0.5rem',
  'p-base': 'padding: 1rem',
  'p-lg': 'padding: 1.75rem',
  'p-xl': 'padding: 2.5rem',
  'p-px': 'padding: 1px',
  'p-1': 'padding: 0.25rem',
  'p-2': 'padding: 0.5rem',
  'p-3': 'padding: 0.75rem',
  'p-4': 'padding: 1rem',
  'p-5': 'padding: 1.25rem',
  'p-6': 'padding: 1.5rem',
  'p-8': 'padding: 2rem',
  'p-10': 'padding: 2.5rem',
  'px-0': 'padding-left: 0; padding-right: 0',
  'px-xs': 'padding-left: 0.25rem; padding-right: 0.25rem',
  'px-sm': 'padding-left: 0.5rem; padding-right: 0.5rem',
  'px-base': 'padding-left: 1rem; padding-right: 1rem',
  'px-lg': 'padding-left: 1.75rem; padding-right: 1.75rem',
  'px-xl': 'padding-left: 2.5rem; padding-right: 2.5rem',
  'px-px': 'padding-left: 1px; padding-right: 1px',
  'px-1': 'padding-left: 0.25rem; padding-right: 0.25rem',
  'px-2': 'padding-left: 0.5rem; padding-right: 0.5rem',
  'px-3': 'padding-left: 0.75rem; padding-right: 0.75rem',
  'px-4': 'padding-left: 1rem; padding-right: 1rem',
  'px-5': 'padding-left: 1.25rem; padding-right: 1.25rem',
  'px-6': 'padding-left: 1.5rem; padding-right: 1.5rem',
  'px-8': 'padding-left: 2rem; padding-right: 2rem',
  'px-10': 'padding-left: 2.5rem; padding-right: 2.5rem',
  'px-12': 'padding-left: 3rem; padding-right: 3rem',
  'px-16': 'padding-left: 4rem; padding-right: 4rem',
  'py-0': 'padding-top: 0; padding-bottom: 0',
  'py-xs': 'padding-top: 0.25rem; padding-bottom: 0.25rem',
  'py-sm': 'padding-top: 0.5rem; padding-bottom: 0.5rem',
  'py-base': 'padding-top: 1rem; padding-bottom: 1rem',
  'py-lg': 'padding-top: 1.75rem; padding-bottom: 1.75rem',
  'py-xl': 'padding-top: 2.5rem; padding-bottom: 2.5rem',
  'py-px': 'padding-top: 1px; padding-bottom: 1px',
  'py-1': 'padding-top: 0.25rem; padding-bottom: 0.25rem',
  'py-2': 'padding-top: 0.5rem; padding-bottom: 0.5rem',
  'py-3': 'padding-top: 0.75rem; padding-bottom: 0.75rem',
  'py-4': 'padding-top: 1rem; padding-bottom: 1rem',
  'py-5': 'padding-top: 1.25rem; padding-bottom: 1.25rem',
  'py-6': 'padding-top: 1.5rem; padding-bottom: 1.5rem',
  'py-8': 'padding-top: 2rem; padding-bottom: 2rem',
  'py-10': 'padding-top: 2.5rem; padding-bottom: 2.5rem',
  'py-12': 'padding-top: 3rem; padding-bottom: 3rem',
  'py-16': 'padding-top: 4rem; padding-bottom: 4rem',
  'pt-0': 'padding-top: 0',
  'pt-xs': 'padding-top: 0.25rem',
  'pt-sm': 'padding-top: 0.5rem',
  'pt-base': 'padding-top: 1rem',
  'pt-lg': 'padding-top: 1.75rem',
  'pt-xl': 'padding-top: 2.5rem',
  'pt-px': 'padding-top: 1px',
  'pt-1': 'padding-top: 0.25rem',
  'pt-2': 'padding-top: 0.5rem',
  'pt-3': 'padding-top: 0.75rem',
  'pt-4': 'padding-top: 1rem',
  'pt-6': 'padding-top: 1.5rem',
  'pt-8': 'padding-top: 2rem',
  'pb-0': 'padding-bottom: 0',
  'pb-xs': 'padding-bottom: 0.25rem',
  'pb-sm': 'padding-bottom: 0.5rem',
  'pb-base': 'padding-bottom: 1rem',
  'pb-lg': 'padding-bottom: 1.75rem',
  'pb-xl': 'padding-bottom: 2.5rem',
  'pb-px': 'padding-bottom: 1px',
  'pb-1': 'padding-bottom: 0.25rem',
  'pb-2': 'padding-bottom: 0.5rem',
  'pb-4': 'padding-bottom: 1rem',
  'pb-6': 'padding-bottom: 1.5rem',
  'pb-8': 'padding-bottom: 2rem',
  'pl-0': 'padding-left: 0',
  'pl-xs': 'padding-left: 0.25rem',
  'pl-sm': 'padding-left: 0.5rem',
  'pl-base': 'padding-left: 1rem',
  'pl-lg': 'padding-left: 1.75rem',
  'pl-xl': 'padding-left: 2.5rem',
  'pl-px': 'padding-left: 1px',
  'pl-1': 'padding-left: 0.25rem',
  'pl-2': 'padding-left: 0.5rem',
  'pl-3': 'padding-left: 0.75rem',
  'pl-4': 'padding-left: 1rem',
  'pl-6': 'padding-left: 1.5rem',
  'pl-8': 'padding-left: 2rem',
  'pr-0': 'padding-right: 0',
  'pr-xs': 'padding-right: 0.25rem',
  'pr-sm': 'padding-right: 0.5rem',
  'pr-base': 'padding-right: 1rem',
  'pr-lg': 'padding-right: 1.75rem',
  'pr-xl': 'padding-right: 2.5rem',
  'pr-px': 'padding-right: 1px',
  'pr-1': 'padding-right: 0.25rem',
  'pr-2': 'padding-right: 0.5rem',
  'pr-3': 'padding-right: 0.75rem',
  'pr-4': 'padding-right: 1rem',
  'pr-6': 'padding-right: 1.5rem',
  'pr-8': 'padding-right: 2rem',
  '-pl-xs': 'padding-left: -0.25rem',
  '-pl-sm': 'padding-left: -0.5rem',
  '-pl-base': 'padding-left: -1rem',
  '-pl-1': 'padding-left: -0.25rem',
  '-pl-2': 'padding-left: -0.5rem',
  '-pl-4': 'padding-left: -1rem',

  // Typography
  'text-left': 'text-align: left',
  'text-center': 'text-align: center',
  'text-right': 'text-align: right',
  'text-justify': 'text-align: justify',
  'text-xs': 'font-size: 0.75rem; line-height: 1rem',
  'text-sm': 'font-size: 0.875rem; line-height: 1.25rem',
  'text-base': 'font-size: 1rem; line-height: 1.5rem',
  'text-lg': 'font-size: 1.125rem; line-height: 1.75rem',
  'text-xl': 'font-size: 1.25rem; line-height: 1.75rem',
  'text-2xl': 'font-size: 1.5rem; line-height: 2rem',
  'text-3xl': 'font-size: 1.875rem; line-height: 2.25rem',
  'text-4xl': 'font-size: 2.25rem; line-height: 2.5rem',
  'text-5xl': 'font-size: 3rem; line-height: 1',
  'font-sans': 'font-family: "Open Sans", ui-sans-serif, system-ui, sans-serif',
  'font-serif': 'font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
  'font-mono': 'font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  'font-thin': 'font-weight: 100',
  'font-light': 'font-weight: 300',
  'font-normal': 'font-weight: 400',
  'font-medium': 'font-weight: 500',
  'font-semibold': 'font-weight: 600',
  'font-bold': 'font-weight: 700',
  'font-extrabold': 'font-weight: 800',
  'font-black': 'font-weight: 900',
  'italic': 'font-style: italic',
  'not-italic': 'font-style: normal',
  'uppercase': 'text-transform: uppercase',
  'lowercase': 'text-transform: lowercase',
  'capitalize': 'text-transform: capitalize',
  'normal-case': 'text-transform: none',
  'underline': 'text-decoration: underline',
  'overline': 'text-decoration: overline',
  'line-through': 'text-decoration: line-through',
  'no-underline': 'text-decoration: none',
  'underline-offset-auto': 'text-underline-offset: auto',
  'underline-offset-2': 'text-underline-offset: 2px',
  'underline-offset-4': 'text-underline-offset: 4px',
  'tracking-tight': 'letter-spacing: -0.025em',
  'tracking-normal': 'letter-spacing: 0',
  'tracking-wide': 'letter-spacing: 0.025em',
  'tracking-wider': 'letter-spacing: 0.05em',
  'tracking-widest': 'letter-spacing: 0.1em',
  'leading-none': 'line-height: 1',
  'leading-tight': 'line-height: 1.25',
  'leading-snug': 'line-height: 1.375',
  'leading-normal': 'line-height: 1.5',
  'leading-relaxed': 'line-height: 1.625',
  'leading-loose': 'line-height: 2',
  'leading-3': 'line-height: .75rem',
  'leading-4': 'line-height: 1rem',
  'leading-5': 'line-height: 1.25rem',
  'leading-6': 'line-height: 1.5rem',
  'leading-7': 'line-height: 1.75rem',
  'leading-8': 'line-height: 2rem',
  'leading-9': 'line-height: 2.25rem',
  'leading-10': 'line-height: 2.5rem',
  'leading-none': 'line-height: 1',
  'leading-tight': 'line-height: 1.25',
  'whitespace-normal': 'white-space: normal',
  'whitespace-nowrap': 'white-space: nowrap',
  'whitespace-pre': 'white-space: pre',
  'whitespace-pre-line': 'white-space: pre-line',
  'whitespace-pre-wrap': 'white-space: pre-wrap',
  'break-normal': 'overflow-wrap: normal; word-break: normal',
  'break-words': 'overflow-wrap: break-word',
  'break-all': 'word-break: break-all',
  'hyphens-none': 'hyphens: none',
  'hyphens-manual': 'hyphens: manual',
  'hyphens-auto': 'hyphens: auto',
  'indent-0': 'text-indent: 0',
  'indent-xs': 'text-indent: 0.25rem',
  'indent-sm': 'text-indent: 0.5rem',
  'indent-base': 'text-indent: 1rem',
  'indent-lg': 'text-indent: 1.75rem',
  'indent-xl': 'text-indent: 2.5rem',
  'vertical-align-baseline': 'vertical-align: baseline',
  'vertical-align-top': 'vertical-align: top',
  'vertical-align-middle': 'vertical-align: middle',
  'vertical-align-bottom': 'vertical-align: bottom',
  'vertical-align-text-top': 'vertical-align: text-top',
  'vertical-align-text-bottom': 'vertical-align: text-bottom',
  'truncate': 'overflow: hidden; text-overflow: ellipsis; white-space: nowrap',
  'text-clip': 'text-overflow: clip',
  'text-overflow-ellipsis': 'text-overflow: ellipsis',
  'select-none': 'user-select: none',
  'select-text': 'user-select: text',
  'select-all': 'user-select: all',
  'select-auto': 'user-select: auto',
  'align-baseline': 'vertical-align: baseline',
  'align-top': 'vertical-align: top',
  'align-middle': 'vertical-align: middle',
  'align-bottom': 'vertical-align: bottom',
  'align-text-top': 'vertical-align: text-top',
  'align-text-bottom': 'vertical-align: text-bottom',

  // Colors
  'text-white': 'color: #ffffff',
  'text-black': 'color: #1f2331',
  'text-current': 'color: currentColor',
  'text-transparent': 'color: transparent',
  'text-neutral-dark': 'color: #5e616b',
  'text-neutral-base': 'color: #92949b',
  'text-neutral-light': 'color: #ededec',
  'text-neutral-lighter': 'color: #f6f6f5',
  'text-primary-light': 'color: #d6eaf0',
  'text-primary-base': 'color: #00607a',
  'text-primary-dark': 'color: #00475c',
  'text-success-light': 'color: #dcf8e2',
  'text-success-base': 'color: #24d14c',
  'text-success-dark': 'color: #1aa23a',
  'text-warning-light': 'color: #fef6b2',
  'text-warning-base': 'color: #fdcb33',
  'text-warning-dark': 'color: #b88e12',
  'text-info-light': 'color: #feebcc',
  'text-info-base': 'color: #fa9902',
  'text-info-dark': 'color: #c97a00',
  'text-alert-light': 'color: #fbd3ce',
  'text-alert-base': 'color: #d22333',
  'text-alert-dark': 'color: #a40014',
  'text-heading-base': 'color: #3c4c5c',
  'text-heading-dark': 'color: #26374a',
  'text-code': 'color: #c10007',
  'bg-white': 'background-color: #ffffff',
  'bg-black': 'background-color: #1f2331',
  'bg-current': 'background-color: currentColor',
  'bg-transparent': 'background-color: transparent',
  'bg-neutral-dark': 'background-color: #5e616b',
  'bg-neutral-base': 'background-color: #92949b',
  'bg-neutral-light': 'background-color: #ededec',
  'bg-neutral-lighter': 'background-color: #f6f6f5',
  'bg-primary-light': 'background-color: #d6eaf0',
  'bg-primary-base': 'background-color: #00607a',
  'bg-primary-dark': 'background-color: #00475c',
  'bg-success-light': 'background-color: #dcf8e2',
  'bg-success-base': 'background-color: #24d14c',
  'bg-success-dark': 'background-color: #1aa23a',
  'bg-warning-light': 'background-color: #fef6b2',
  'bg-warning-base': 'background-color: #fdcb33',
  'bg-warning-dark': 'background-color: #b88e12',
  'bg-info-light': 'background-color: #feebcc',
  'bg-info-base': 'background-color: #fa9902',
  'bg-info-dark': 'background-color: #c97a00',
  'bg-alert-light': 'background-color: #fbd3ce',
  'bg-alert-base': 'background-color: #d22333',
  'bg-alert-dark': 'background-color: #a40014',
  'bg-heading-base': 'background-color: #3c4c5c',
  'bg-heading-dark': 'background-color: #26374a',
  'border-white': 'border-color: #ffffff',
  'border-black': 'border-color: #1f2331',
  'border-current': 'border-color: currentColor',
  'border-neutral-dark': 'border-color: #5e616b',
  'border-neutral-base': 'border-color: #92949b',
  'border-neutral-light': 'border-color: #ededec',
  'border-neutral-lighter': 'border-color: #f6f6f5',
  'border-primary-light': 'border-color: #d6eaf0',
  'border-primary-base': 'border-color: #00607a',
  'border-primary-dark': 'border-color: #00475c',
  'border-success-light': 'border-color: #dcf8e2',
  'border-success-base': 'border-color: #24d14c',
  'border-success-dark': 'border-color: #1aa23a',
  'border-warning-light': 'border-color: #fef6b2',
  'border-warning-base': 'border-color: #fdcb33',
  'border-warning-dark': 'border-color: #b88e12',
  'border-info-light': 'border-color: #feebcc',
  'border-info-base': 'border-color: #fa9902',
  'border-info-dark': 'border-color: #c97a00',
  'border-alert-light': 'border-color: #fbd3ce',
  'border-alert-base': 'border-color: #d22333',
  'border-alert-dark': 'border-color: #a40014',
  'border-heading-base': 'border-color: #3c4c5c',
  'border-heading-dark': 'border-color: #26374a',
  'fill-current': 'fill: currentColor',
  'fill-neutral-dark': 'fill: #5e616b',
  'fill-neutral-base': 'fill: #92949b',
  'fill-neutral-light': 'fill: #ededec',
  'fill-neutral-lighter': 'fill: #f6f6f5',
  'fill-primary-base': 'fill: #00607a',
  'fill-primary-dark': 'fill: #00475c',
  'fill-success-base': 'fill: #24d14c',
  'fill-alert-base': 'fill: #d22333',
  'fill-white': 'fill: #ffffff',
  'fill-black': 'fill: #1f2331',
  'fill-warning-base': 'fill: #fdcb33',
  'fill-info-base': 'fill: #fa9902',
  'stroke-current': 'stroke: currentColor',
  'stroke-white': 'stroke: #ffffff',
  'stroke-black': 'stroke: #1f2331',
  'stroke-neutral-dark': 'stroke: #5e616b',
  'stroke-neutral-base': 'stroke: #92949b',
  'stroke-primary-base': 'stroke: #00607a',
  'stroke-success-base': 'stroke: #24d14c',
  'stroke-alert-base': 'stroke: #d22333',

  // Border
  'border-0': 'border-width: 0',
  'border': 'border-width: 1px; border-style: solid',
  'border-2': 'border-width: 2px; border-style: solid',
  'border-4': 'border-width: 4px; border-style: solid',
  'border-8': 'border-width: 8px; border-style: solid',
  'border-b-0': 'border-bottom-width: 0',
  'border-b': 'border-bottom-width: 1px; border-bottom-style: solid',
  'border-b-2': 'border-bottom-width: 2px; border-bottom-style: solid',
  'border-b-4': 'border-bottom-width: 4px; border-bottom-style: solid',
  'border-t-0': 'border-top-width: 0',
  'border-t': 'border-top-width: 1px; border-top-style: solid',
  'border-t-2': 'border-top-width: 2px; border-top-style: solid',
  'border-t-4': 'border-top-width: 4px; border-top-style: solid',
  'border-l-0': 'border-left-width: 0',
  'border-l': 'border-left-width: 1px; border-left-style: solid',
  'border-l-2': 'border-left-width: 2px; border-left-style: solid',
  'border-l-4': 'border-left-width: 4px; border-left-style: solid',
  'border-r-0': 'border-right-width: 0',
  'border-r': 'border-right-width: 1px; border-right-style: solid',
  'border-r-2': 'border-right-width: 2px; border-right-style: solid',
  'border-r-4': 'border-right-width: 4px; border-right-style: solid',
  'border-solid': 'border-style: solid',
  'border-dashed': 'border-style: dashed',
  'border-dotted': 'border-style: dotted',
  'border-none': 'border-style: none',
  'border-collapse': 'border-collapse: collapse',
  'border-separate': 'border-collapse: separate',

  // Border Radius
  'rounded-none': 'border-radius: 0',
  'rounded': 'border-radius: 0.1875rem',
  'rounded-sm': 'border-radius: 0.125rem',
  'rounded-xs': 'border-radius: 0.0625rem',
  'rounded-md': 'border-radius: 0.375rem',
  'rounded-lg': 'border-radius: 0.5rem',
  'rounded-xl': 'border-radius: 0.75rem',
  'rounded-2xl': 'border-radius: 1rem',
  'rounded-full': 'border-radius: 9999px',
  'rounded-t-none': 'border-top-left-radius: 0; border-top-right-radius: 0',
  'rounded-t': 'border-top-left-radius: 0.1875rem; border-top-right-radius: 0.1875rem',
  'rounded-t-sm': 'border-top-left-radius: 0.125rem; border-top-right-radius: 0.125rem',
  'rounded-t-md': 'border-top-left-radius: 0.375rem; border-top-right-radius: 0.375rem',
  'rounded-t-lg': 'border-top-left-radius: 0.5rem; border-top-right-radius: 0.5rem',
  'rounded-t-full': 'border-top-left-radius: 9999px; border-top-right-radius: 9999px',
  'rounded-b-none': 'border-bottom-left-radius: 0; border-bottom-right-radius: 0',
  'rounded-b': 'border-bottom-left-radius: 0.1875rem; border-bottom-right-radius: 0.1875rem',
  'rounded-b-sm': 'border-bottom-left-radius: 0.125rem; border-bottom-right-radius: 0.125rem',
  'rounded-b-md': 'border-bottom-left-radius: 0.375rem; border-bottom-right-radius: 0.375rem',
  'rounded-b-lg': 'border-bottom-left-radius: 0.5rem; border-bottom-right-radius: 0.5rem',
  'rounded-b-full': 'border-bottom-left-radius: 9999px; border-bottom-right-radius: 9999px',
  'rounded-l-none': 'border-top-left-radius: 0; border-bottom-left-radius: 0',
  'rounded-l': 'border-top-left-radius: 0.1875rem; border-bottom-left-radius: 0.1875rem',
  'rounded-l-sm': 'border-top-left-radius: 0.125rem; border-bottom-left-radius: 0.125rem',
  'rounded-l-lg': 'border-top-left-radius: 0.5rem; border-bottom-left-radius: 0.5rem',
  'rounded-l-full': 'border-top-left-radius: 9999px; border-bottom-left-radius: 9999px',
  'rounded-r-none': 'border-top-right-radius: 0; border-bottom-right-radius: 0',
  'rounded-r': 'border-top-right-radius: 0.1875rem; border-bottom-right-radius: 0.1875rem',
  'rounded-r-sm': 'border-top-right-radius: 0.125rem; border-bottom-right-radius: 0.125rem',
  'rounded-r-lg': 'border-top-right-radius: 0.5rem; border-bottom-right-radius: 0.5rem',
  'rounded-r-full': 'border-top-right-radius: 9999px; border-bottom-right-radius: 9999px',
  'rounded-tl-none': 'border-top-left-radius: 0',
  'rounded-tl': 'border-top-left-radius: 0.1875rem',
  'rounded-tl-sm': 'border-top-left-radius: 0.125rem',
  'rounded-tl-md': 'border-top-left-radius: 0.375rem',
  'rounded-tl-lg': 'border-top-left-radius: 0.5rem',
  'rounded-tr-none': 'border-top-right-radius: 0',
  'rounded-tr': 'border-top-right-radius: 0.1875rem',
  'rounded-tr-sm': 'border-top-right-radius: 0.125rem',
  'rounded-tr-md': 'border-top-right-radius: 0.375rem',
  'rounded-tr-lg': 'border-top-right-radius: 0.5rem',
  'rounded-br-none': 'border-bottom-right-radius: 0',
  'rounded-br': 'border-bottom-right-radius: 0.1875rem',
  'rounded-br-sm': 'border-bottom-right-radius: 0.125rem',
  'rounded-br-md': 'border-bottom-right-radius: 0.375rem',
  'rounded-br-lg': 'border-bottom-right-radius: 0.5rem',
  'rounded-bl-none': 'border-bottom-left-radius: 0',
  'rounded-bl': 'border-bottom-left-radius: 0.1875rem',
  'rounded-bl-sm': 'border-bottom-left-radius: 0.125rem',
  'rounded-bl-md': 'border-bottom-left-radius: 0.375rem',
  'rounded-bl-lg': 'border-bottom-left-radius: 0.5rem',

  // Box Shadow
  'shadow-sm': 'box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05)',
  'shadow': 'box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
  'shadow-md': 'box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  'shadow-lg': 'box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
  'shadow-xl': 'box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  'shadow-2xl': 'box-shadow: 0 25px 50px -12px rgb(0 0 0 / 0.25)',
  'shadow-none': 'box-shadow: none',
  'shadow-outline-alert': 'box-shadow: 0 0 0 2px #d22333',
  'shadow-outline-warning': 'box-shadow: 0 0 0 3px #fdcb33',
  'shadow-outline-black': 'box-shadow: 0 0 0 3px #1f2331',
  'shadow-outline-focus': 'box-shadow: inset 0 -2px 0 0 #1f2331',
  'shadow-outline-input': 'box-shadow: inset 0 0 0 3px #1f2331',
  'shadow-solid-primary-base': 'box-shadow: 0 1px 0 0 #00607a',
  'shadow-solid-primary-light': 'box-shadow: 0 1px 0 0 #d6eaf0',
  'shadow-solid-primary-dark': 'box-shadow: 0 1px 0 0 #00475c',
  'shadow-solid-alert-base': 'box-shadow: 0 1px 0 0 #d22333',
  'shadow-solid-alert-dark': 'box-shadow: 0 1px 0 0 #a40014',
  'shadow-solid-neutral-base': 'box-shadow: 0 1px 0 0 #92949b',
  'shadow-solid-black': 'box-shadow: 0 1px 0 0 #1f2331',
  'shadow-focus': 'box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.05)',
  'shadow-inner': 'box-shadow: inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',

  // Effects
  'opacity-0': 'opacity: 0',
  'opacity-25': 'opacity: 0.25',
  'opacity-50': 'opacity: 0.5',
  'opacity-75': 'opacity: 0.75',
  'opacity-100': 'opacity: 1',
  'mix-blend-normal': 'mix-blend-mode: normal',
  'mix-blend-multiply': 'mix-blend-mode: multiply',
  'mix-blend-screen': 'mix-blend-mode: screen',
  'mix-blend-overlay': 'mix-blend-mode: overlay',
  'mix-blend-darken': 'mix-blend-mode: darken',
  'mix-blend-lighten': 'mix-blend-mode: lighten',
  'mix-blend-color-dodge': 'mix-blend-mode: color-dodge',
  'mix-blend-color-burn': 'mix-blend-mode: color-burn',
  'mix-blend-hard-light': 'mix-blend-mode: hard-light',
  'mix-blend-soft-light': 'mix-blend-mode: soft-light',
  'mix-blend-difference': 'mix-blend-mode: difference',
  'mix-blend-exclusion': 'mix-blend-mode: exclusion',
  'mix-blend-hue': 'mix-blend-mode: hue',
  'mix-blend-saturation': 'mix-blend-mode: saturation',
  'mix-blend-color': 'mix-blend-mode: color',
  'mix-blend-luminosity': 'mix-blend-mode: luminosity',
  'bg-blend-normal': 'background-blend-mode: normal',
  'bg-blend-multiply': 'background-blend-mode: multiply',
  'bg-blend-screen': 'background-blend-mode: screen',
  'bg-blend-overlay': 'background-blend-mode: overlay',
  'bg-blend-darken': 'background-blend-mode: darken',
  'bg-blend-lighten': 'background-blend-mode: lighten',
  'bg-blend-color-dodge': 'background-blend-mode: color-dodge',
  'bg-blend-color-burn': 'background-blend-mode: color-burn',
  'bg-blend-hard-light': 'background-blend-mode: hard-light',
  'bg-blend-soft-light': 'background-blend-mode: soft-light',
  'bg-blend-difference': 'background-blend-mode: difference',
  'bg-blend-exclusion': 'background-blend-mode: exclusion',
  'bg-blend-color': 'background-blend-mode: color',
  'bg-blend-luminosity': 'background-blend-mode: luminosity',

  // Tables
  'border-collapse': 'border-collapse: collapse',
  'border-separate': 'border-collapse: separate',
  'table-auto': 'table-layout: auto',
  'table-fixed': 'table-layout: fixed',

  // Transitions
  'transition-none': 'transition: none',
  'transition-all': 'transition-property: all; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms',
  'transition': 'transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms',
  'transition-colors': 'transition-property: color, background-color, border-color, text-decoration-color, fill, stroke; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms',
  'transition-opacity': 'transition-property: opacity; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms',
  'transition-shadow': 'transition-property: box-shadow; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms',
  'transition-transform': 'transition-property: transform; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms',
  'transition-none': 'transition: none',
  'duration-0': 'transition-duration: 0s',
  'duration-75': 'transition-duration: 75ms',
  'duration-100': 'transition-duration: 100ms',
  'duration-150': 'transition-duration: 150ms',
  'duration-200': 'transition-duration: 200ms',
  'duration-300': 'transition-duration: 300ms',
  'duration-500': 'transition-duration: 500ms',
  'duration-700': 'transition-duration: 700ms',
  'duration-1000': 'transition-duration: 1000ms',
  'ease-linear': 'transition-timing-function: linear',
  'ease-in': 'transition-timing-function: cubic-bezier(0.4, 0, 1, 1)',
  'ease-out': 'transition-timing-function: cubic-bezier(0, 0, 0.2, 1)',
  'ease-in-out': 'transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1)',
  'delay-0': 'transition-delay: 0s',
  'delay-75': 'transition-delay: 75ms',
  'delay-100': 'transition-delay: 100ms',
  'delay-150': 'transition-delay: 150ms',
  'delay-200': 'transition-delay: 200ms',
  'delay-300': 'transition-delay: 300ms',
  'delay-500': 'transition-delay: 500ms',
  'delay-1000': 'transition-delay: 1000ms',

  // Transform
  'transform': 'transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'transform-gpu': 'transform: translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), 0) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'transform-none': 'transform: none',
  'origin-center': 'transform-origin: center',
  'origin-top': 'transform-origin: top',
  'origin-top-right': 'transform-origin: top right',
  'origin-right': 'transform-origin: right',
  'origin-bottom-right': 'transform-origin: bottom right',
  'origin-bottom': 'transform-origin: bottom',
  'origin-bottom-left': 'transform-origin: bottom left',
  'origin-left': 'transform-origin: left',
  'origin-top-left': 'transform-origin: top left',
  'scale-0': '--tw-scale-x: 0; --tw-scale-y: 0; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(0, 0)',
  'scale-50': '--tw-scale-x: 0.5; --tw-scale-y: 0.5; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(0.5, 0.5)',
  'scale-75': '--tw-scale-x: 0.75; --tw-scale-y: 0.75; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(0.75, 0.75)',
  'scale-90': '--tw-scale-x: 0.9; --tw-scale-y: 0.9; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(0.9, 0.9)',
  'scale-95': '--tw-scale-x: 0.95; --tw-scale-y: 0.95; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(0.95, 0.95)',
  'scale-100': '--tw-scale-x: 1; --tw-scale-y: 1; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(1, 1)',
  'scale-105': '--tw-scale-x: 1.05; --tw-scale-y: 1.05; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(1.05, 1.05)',
  'scale-110': '--tw-scale-x: 1.1; --tw-scale-y: 1.1; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(1.1, 1.1)',
  'scale-125': '--tw-scale-x: 1.25; --tw-scale-y: 1.25; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(1.25, 1.25)',
  'scale-150': '--tw-scale-x: 1.5; --tw-scale-y: 1.5; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(1.5, 1.5)',
  'scale-x-0': '--tw-scale-x: 0; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'scale-x-50': '--tw-scale-x: 0.5; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(0.5, var(--tw-scale-y, 1))',
  'scale-x-100': '--tw-scale-x: 1; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(1, var(--tw-scale-y, 1))',
  'scale-y-0': '--tw-scale-y: 0; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), 0)',
  'scale-y-50': '--tw-scale-y: 0.5; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), 0.5)',
  'scale-y-100': '--tw-scale-y: 1; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), 1)',
  'rotate-0': '--tw-rotate: 0deg; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(0) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'rotate-45': '--tw-rotate: 45deg; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(45deg) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'rotate-90': '--tw-rotate: 90deg; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(90deg) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'rotate-180': '--tw-rotate: 180deg; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(180deg) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-rotate-45': '--tw-rotate: -45deg; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(-45deg) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-rotate-90': '--tw-rotate: -90deg; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(-90deg) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-rotate-180': '--tw-rotate: -180deg; transform: translateX(var(--tw-translate-x, 0)) translateY(var(--tw-translate-y, 0)) rotate(-180deg) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'translate-x-0': '--tw-translate-x: 0; transform: translateX(0) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'translate-x-px': '--tw-translate-x: 1px; transform: translateX(1px) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'translate-x-0\\.5': '--tw-translate-x: 0.125rem; transform: translateX(0.125rem) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-x-0': '--tw-translate-x: 0; transform: translateX(0) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-x-px': '--tw-translate-x: -1px; transform: translateX(-1px) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-x-1': '--tw-translate-x: -0.25rem; transform: translateX(-0.25rem) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-x-2': '--tw-translate-x: -0.5rem; transform: translateX(-0.5rem) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-x-4': '--tw-translate-x: -1rem; transform: translateX(-1rem) translateY(var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'translate-y-px': '--tw-translate-y: 1px; transform: translateX(var(--tw-translate-x, 0)) translateY(1px) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-y-px': '--tw-translate-y: -1px; transform: translateX(var(--tw-translate-x, 0)) translateY(-1px) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-y-1': '--tw-translate-y: -0.25rem; transform: translateX(var(--tw-translate-x, 0)) translateY(-0.25rem) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-y-2': '--tw-translate-y: -0.5rem; transform: translateX(var(--tw-translate-x, 0)) translateY(-0.5rem) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  '-translate-y-4': '--tw-translate-y: -1rem; transform: translateX(var(--tw-translate-x, 0)) translateY(-1rem) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',
  'translate-y-full': '--tw-translate-y: 100%; transform: translateX(var(--tw-translate-x, 0)) translateY(100%) rotate(var(--tw-rotate, 0)) scale(var(--tw-scale-x, 1), var(--tw-scale-y, 1))',

  // Cursor
  'cursor-auto': 'cursor: auto',
  'cursor-default': 'cursor: default',
  'cursor-pointer': 'cursor: pointer',
  'cursor-wait': 'cursor: wait',
  'cursor-text': 'cursor: text',
  'cursor-move': 'cursor: move',
  'cursor-help': 'cursor: help',
  'cursor-not-allowed': 'cursor: not-allowed',
  'cursor-none': 'cursor: none',
  'cursor-context-menu': 'cursor: context-menu',
  'cursor-progress': 'cursor: progress',
  'cursor-cell': 'cursor: cell',
  'cursor-crosshair': 'cursor: crosshair',
  'cursor-vertical-text': 'cursor: vertical-text',
  'cursor-alias': 'cursor: alias',
  'cursor-copy': 'cursor: copy',
  'cursor-no-drop': 'cursor: no-drop',
  'cursor-grab': 'cursor: grab',
  'cursor-grabbing': 'cursor: grabbing',
  'cursor-all-scroll': 'cursor: all-scroll',
  'cursor-col-resize': 'cursor: col-resize',
  'cursor-row-resize': 'cursor: row-resize',
  'cursor-n-resize': 'cursor: n-resize',
  'cursor-e-resize': 'cursor: e-resize',
  'cursor-s-resize': 'cursor: s-resize',
  'cursor-w-resize': 'cursor: w-resize',
  'cursor-ne-resize': 'cursor: ne-resize',
  'cursor-nw-resize': 'cursor: nw-resize',
  'cursor-se-resize': 'cursor: se-resize',
  'cursor-sw-resize': 'cursor: sw-resize',
  'cursor-ew-resize': 'cursor: ew-resize',
  'cursor-ns-resize': 'cursor: ns-resize',
  'cursor-nesw-resize': 'cursor: nesw-resize',
  'cursor-nwse-resize': 'cursor: nwse-resize',
  'cursor-zoom-in': 'cursor: zoom-in',
  'cursor-zoom-out': 'cursor: zoom-out',

  // Pointer events
  'pointer-events-none': 'pointer-events: none',
  'pointer-events-auto': 'pointer-events: auto',

  // Resize
  'resize-none': 'resize: none',
  'resize': 'resize: both',
  'resize-y': 'resize: vertical',
  'resize-x': 'resize: horizontal',

  // Scroll
  'scroll-auto': 'scroll-behavior: auto',
  'scroll-smooth': 'scroll-behavior: smooth',
  'scroll-normal': 'scroll-behavior: auto',
  'overflow-auto': 'overflow: auto',
  'overflow-hidden': 'overflow: hidden',
  'overflow-visible': 'overflow: visible',
  'overflow-scroll': 'overflow: scroll',
  'overflow-x-auto': 'overflow-x: auto',
  'overflow-y-auto': 'overflow-y: auto',
  'overflow-x-hidden': 'overflow-x: hidden',
  'overflow-y-hidden': 'overflow-y: hidden',
  'overflow-x-visible': 'overflow-x: visible',
  'overflow-y-visible': 'overflow-y: visible',
  'overflow-x-scroll': 'overflow-x: scroll',
  'overflow-y-scroll': 'overflow-y: scroll',
  'snap-none': 'scroll-snap-type: none',
  'snap-x': 'scroll-snap-type: x var(--tw-scroll-snap-strictness)',
  'snap-y': 'scroll-snap-type: y var(--tw-scroll-snap-strictness)',
  'snapboth': 'scroll-snap-type: both var(--tw-scroll-snap-strictness)',
  'snap-mandatory': '--tw-scroll-snap-strictness: mandatory',
  'snap-proximity': '--tw-scroll-snap-strictness: proximity',
  'snap-start': 'scroll-snap-align: start',
  'snap-end': 'scroll-snap-align: end',
  'snap-center': 'scroll-snap-align: center',
  'snap-align-none': 'scroll-snap-align: none',
  'will-change-auto': 'will-change: auto',
  'will-change-scroll': 'will-change: scroll-position',
  'will-change-contents': 'will-change: contents',
  'will-change-transform': 'will-change: transform',

  // SVG
  'fill-none': 'fill: none',

  // Object fit
  'object-contain': 'object-fit: contain',
  'object-cover': 'object-fit: cover',
  'object-fill': 'object-fit: fill',
  'object-none': 'object-fit: none',
  'object-scale-down': 'object-fit: scale-down',
  'object-bottom': 'object-position: bottom',
  'object-center': 'object-position: center',
  'object-left': 'object-position: left',
  'object-left-bottom': 'object-position: left bottom',
  'object-left-top': 'object-position: left top',
  'object-right': 'object-position: right',
  'object-right-bottom': 'object-position: right bottom',
  'object-right-top': 'object-position: right top',
  'object-top': 'object-position: top',

  // Background attachment
  'bg-fixed': 'background-attachment: fixed',
  'bg-local': 'background-attachment: local',
  'bg-scroll': 'background-attachment: scroll',

  // Background repeat
  'bg-repeat': 'background-repeat: repeat',
  'bg-no-repeat': 'background-repeat: no-repeat',
  'bg-repeat-x': 'background-repeat: repeat-x',
  'bg-repeat-y': 'background-repeat: repeat-y',
  'bg-repeat-round': 'background-repeat: round',
  'bg-repeat-space': 'background-repeat: space',

  // Background size
  'bg-auto': 'background-size: auto',
  'bg-cover': 'background-size: cover',
  'bg-contain': 'background-size: contain',

  // List styles
  'list-none': 'list-style-type: none',
  'list-disc': 'list-style-type: disc',
  'list-decimal': 'list-style-type: decimal',
  'list-circle': 'list-style-type: circle',
  'list-square': 'list-style-type: square',
  'list-inside': 'list-style-position: inside',
  'list-outside': 'list-style-position: outside',

  // Outline
  'outline-none': 'outline: 2px solid transparent; outline-offset: 2px',
  'outline': 'outline-width: 2px; outline-style: solid',
  'outline-0': 'outline-width: 0',
  'outline-2': 'outline-width: 2px',
  'outline-4': 'outline-width: 4px',
  'outline-offset-0': 'outline-offset: 0',
  'outline-offset-2': 'outline-offset: 2px',
  'outline-offset-4': 'outline-offset: 4px',
  'outline-offset-auto': 'outline-offset: auto',

  // Ring
  'ring-0': '--tw-ring-offset-shadow: 0 0 #000; --tw-ring-shadow: 0 0 0 0 #000; box-shadow: var(--tw-ring-offset-shadow, 0 0 #000), var(--tw-ring-shadow, 0 0 0 #000), var(--tw-shadow, 0 0 #000)',
  'ring-1': '--tw-ring-offset-shadow: 0 0 #000; --tw-ring-shadow: 0 0 0 1px #000; box-shadow: var(--tw-ring-offset-shadow, 0 0 #000), var(--tw-ring-shadow, 0 0 0 1px #000), var(--tw-shadow, 0 0 #000)',
  'ring-2': '--tw-ring-offset-shadow: 0 0 #000; --tw-ring-shadow: 0 0 0 2px #000; box-shadow: var(--tw-ring-offset-shadow, 0 0 #000), var(--tw-ring-shadow, 0 0 0 2px #000), var(--tw-shadow, 0 0 #000)',
  'ring-4': '--tw-ring-offset-shadow: 0 0 #000; --tw-ring-shadow: 0 0 0 4px #000; box-shadow: var(--tw-ring-offset-shadow, 0 0 #000), var(--tw-ring-shadow, 0 0 0 4px #000), var(--tw-shadow, 0 0 #000)',
  'ring-8': '--tw-ring-offset-shadow: 0 0 #000; --tw-ring-shadow: 0 0 0 8px #000; box-shadow: var(--tw-ring-offset-shadow, 0 0 #000), var(--tw-ring-shadow, 0 0 0 8px #000), var(--tw-shadow, 0 0 #000)',
  'ring-inset': '--tw-ring-offset-shadow: 0 0 0 var(--tw-ring-offset-width, 0px) var(--tw-ring-offset-color, #fff); --tw-ring-shadow: inset 0 0 0 var(--tw-ring-offset-width, 0px) var(--tw-ring-offset-color, #fff); --tw-ring-shadow: inset 0 0 0 var(--tw-ring-width, 0px) var(--tw-ring-color, #000); box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow)',
  'ring-white': '--tw-ring-color: #ffffff',
  'ring-black': '--tw-ring-color: #1f2331',
  'ring-primary-base': '--tw-ring-color: #00607a',
  'ring-primary-light': '--tw-ring-color: #d6eaf0',
  'ring-primary-dark': '--tw-ring-color: #00475c',
  'ring-success-base': '--tw-ring-color: #24d14c',
  'ring-warning-base': '--tw-ring-color: #fdcb33',
  'ring-alert-base': '--tw-ring-color: #d22333',
  'ring-offset-0': '--tw-ring-offset-width: 0px',
  'ring-offset-2': '--tw-ring-offset-width: 2px',
  'ring-offset-4': '--tw-ring-offset-width: 4px',

  // Z-index
  'z-0': 'z-index: 0',
  'z-10': 'z-index: 10',
  'z-20': 'z-index: 20',
  'z-30': 'z-index: 30',
  'z-40': 'z-index: 40',
  'z-50': 'z-index: 50',
  'z-auto': 'z-index: auto',
  'z-max': 'z-index: 999999',

  // Content
  'content-none': 'content: none',

  // Placeholder
  'placeholder-neutral-dark': '::placeholder { color: #5e616b }',
  'placeholder-neutral-base': '::placeholder { color: #92949b }',
  'placeholder-neutral-light': '::placeholder { color: #ededec }',
  'placeholder-primary-light': '::placeholder { color: #d6eaf0 }',
  'placeholder-primary-base': '::placeholder { color: #00607a }',
  'placeholder-alert-base': '::placeholder { color: #d22333 }',
  'placeholder-transparent': '::placeholder { color: transparent }',

  // Misc
  'antialiased': '-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale',
  'subpixel-antialiased': '-webkit-font-smoothing: auto; -moz-osx-font-smoothing: auto',
  'sr-only': 'position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border-width: 0',
  'not-sr-only': 'position: static; width: auto; height: auto; padding: 0; margin: 0; overflow: visible; clip: auto; white-space: normal',
  'isolate': 'isolation: isolate',
  'isolation-auto': 'isolation: auto',
  'forced-color-adjust-none': 'forced-color-adjust: none',
  'forced-color-adjust-auto': 'forced-color-adjust: auto',
  'appearance-none': 'appearance: none',
  'appearance-auto': 'appearance: auto',
  'clip-none': 'clip-path: none',
  'clip-auto': 'clip-path: auto',
  'print-color-adjust-exact': 'print-color-adjust: exact; -webkit-print-color-adjust: exact',
  'print-color-adjust-economy': 'print-color-adjust: economy; -webkit-print-color-adjust: economy',
  'color-scheme-normal': 'color-scheme: normal',
  'color-scheme-dark': 'color-scheme: dark',
  'color-scheme-light': 'color-scheme: light',
  'color-scheme-only': 'color-scheme: only',
  'accent-auto': 'accent-color: auto',
  'accent-primary-base': 'accent-color: #00607a',
  'accent-alert-base': 'accent-color: #d22333',
  'accent-success-base': 'accent-color: #24d14c',
  'accent-warning-base': 'accent-color: #fdcb33',
  'accent-info-base': 'accent-color: #fa9902',
};

function processApply(content) {
  // Replace @apply utility!; with the CSS value
  return content.replace(/@apply\s+([\w-]+!)\s*;/g, (match, util) => {
    const clean = util.replace('!', '');
    const key = clean;
    const val = UTILITIES[key];
    if (val) {
      return `${val} !important`;
    }
    return match; // Keep original if not found
  }).replace(/@apply\s+([\w-]+)\s*;/g, (match, util) => {
    const val = UTILITIES[util];
    if (val) {
      return `${val};`;
    }
    return match; // Keep original if not found
  });
}

function processFile(content) {
  // Remove @tailwind directives
  let result = content.replace(/@tailwind[^;]+;/g, '');
  // Remove @layer declarations but keep their contents
  result = result.replace(/@layer\s+[^{]+\{/g, '{');
  // Process @apply
  result = processApply(result);
  return result;
}

const base = '/root/.openclaw/workspace/projects/desy-react/.storybook/styles/templates/components';
const outPath = '/root/.openclaw/workspace/projects/desy-react/.storybook/styles/desy-html-components.css';

const componentFiles = fs.readdirSync(base);

let allCss = '';

for (const name of componentFiles) {
  const cssFile = `${base}/${name}/_styles.${name}.css`;
  if (!fs.existsSync(cssFile)) continue;
  
  let css = fs.readFileSync(cssFile, 'utf8');
  css = processFile(css);
  allCss += `\n/* ${name} */\n` + css;
}

// Also process base CSS
const baseDir = '/root/.openclaw/workspace/projects/desy-react/.storybook/styles/css';
if (fs.existsSync(baseDir)) {
  for (const f of fs.readdirSync(baseDir)) {
    if (!f.endsWith('.css')) continue;
    let css = fs.readFileSync(`${baseDir}/${f}`, 'utf8');
    css = processFile(css);
    allCss += `\n/* base: ${f} */\n` + css;
  }
}

fs.writeFileSync(outPath, allCss);
console.log(`Written ${allCss.length} bytes to ${outPath}`);
console.log(`c-toggle occurrences: ${(allCss.match(/c-toggle/g) || []).length}`);
console.log(`c-button occurrences: ${(allCss.match(/c-button/g) || []).length}`);
